apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-v1-config
data:
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "192.168.1.107"
  DB_PORT: "5432"
  PORT: "3000"
