apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: product-service-v1
  namespace: argocd
spec: 
  destination: 
    namespace: taller3
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: product-service-v1
    repoURL: "https://github.com/oojeda/master-kubernetes.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
