apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-v1-config
data:
  DB_NAME: "postgress"
  DB_USER: "postgress"
  DB_PASSWORD: "postgress"
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  PORT: "3000"
